on:
  push:
    branches:
    - main

jobs: 
  Build_App: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Build app 
        run : npm install
              npm run build
