on:
  push:
    branches:
    - main
env: 
  EB_PACKAGE_S3_BUCKET_NAME: "spendly-deploy-builds"
  EB_APP_NAME              : "spendly"
  EB_ENVIRONMENT_NAME      : "Spendly-env"
  DEPLOY_PACKAGE_NAME      : "Spendly-package-${{ github.sha }}.zip"
  AWS_REGION_NAME          : "us-east-1"
  
  
jobs: 
  ci_process: 
    environment: Actions Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      
      - name: Build app 
        run : npm install
              npm run build
      - name: Create ZIP deploy package 
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

      - name: Configure AWS Credentials
        uses : aws-actions/configure-aws-credentials@v5.1.1
        with: 
          aws-access-key-id      : ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key  : ${{ secrets.AWS_SECRET_KEY }}
          aws-region             : ${{ env.AWS_REGION_NAME }}
      - name: Copy Zip package to S3 bucket
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/















      
